### ISSUE TITLE
Kendra context summary encoding/decoding issues.

### ISSUE THREAD

**Issue by cboin1996** [aws-solutions/qnabot-on-aws#700]
**Describe the bug**
I have a QnaBot that has a kendra index loading CSV's and PDF documents from an S3 bucket.
The bot is integrated with bedrock via the LLM plugin.  The summarized responses include the `Context` dropdown. When I click the `Context` drop-down, it seems that `â€¢`'s are appearing in place of the proper characters.

I quickly read about encoding's here: https://stackoverflow.com/questions/2477452/%C3%A2%E2%82%AC-showing-on-page-instead-of

When checking the `FulfillmentLambda` logs, it appears `Kendra` is in fact returning it's queries with these
characters, so it gets passed along through bot fulfilliment, to the llm lambda, and then back to the client interface.

![image (11)](https://github.com/aws-solutions/qnabot-on-aws/assets/38514413/77421383-062c-4498-85c7-9f577e960b28)

**To Reproduce**

Create a Kendra index, upload a PDF containing `&` or `’` and perhaps the issue will re-produce.

**Expected behavior**
I wonder if it is possible to intercept these symbols, or re-encode the queries produced by kendra in bot-fulfillment with UTF-8 before handing it off to the llm lambdas.

**Please complete the following information about the solution:**
- [x] Version: v5.5.0
- [x] Region: [e.g. ca-central-1]
- [x] Was the solution modified from the version published on this repository? ***Yes.***

These changes were merged via a yaml merge.

```yaml
Resources:
  # Modified UserPool including custom welcome message to point to the chat client.
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:
        Fn::Join:
          - '-'
          - - UserPool
            - Ref: AWS::StackName
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly:
          Fn::If:
            - AdminSignUp
            - true
            - false
        InviteMessageTemplate:
          EmailMessage:
            Fn::Sub: |
              <p>Hello {username},
              <p>Welcome to QnABot! Your temporary password is:
              <p>     {####}
              <p>
              <p>When the CloudFormation stack is COMPLETE, use the link belows to interact with qnabot.
              <p>
              <p>To access the chat client, use the below link:
              <p>     ${ApiUrl.Name}/pages/client
              <p>
              <p>The below link is only accessible by admins:
              <p>     ${ApiUrl.Name}/pages/designer
              <p>
              <p>Good luck!
              <p>QnABot (www.amazon.com/qnabot)
          EmailSubject: Welcome to QnABot!
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Required: true
          Name: email
          AttributeDataType: String
          Mutable: true
      LambdaConfig:
        CustomMessage:
          Fn::GetAtt:
            - MessageLambda
            - Arn
        PreSignUp:
          Fn::GetAtt:
            - SignupLambda
            - Arn

Outputs:

  # Additional output from qnabot-addons.yaml that creates
  # an output for the api gateway.
  QnaBotAddonApiGatewayId:
    Description: Id of the QnaBot ApiGateway
    Value: !Ref API
    Export:
      Name: !Sub "qnabot-addon-api-gateway-api-id"

  ## create an output for the api gateway stage name
  QnaBotAddonApiGatewayStageName:
    Description: Name of Qnabot ApiGateway Stage
    Value: !Ref Stage
    Export:
      Name: !Sub "qnabot-addon-api-gateway-stage-name"
```

- [x] If the answer to the previous question was yes, are the changes available on GitHub? ***No***
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? No, but this is unrelated.
- [x] Were there any errors in the CloudWatch Logs? ***No Errors.***

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
